#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m config debug_output on
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          on            \
    focus_follows_mouse          autoraise            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xffff9910     \
    normal_window_border_color   0xff555555     \
    window_border_width          3              \
    window_border_radius         10             \
    window_border_blur           on            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  06            \
    bottom_padding               06             \
    left_padding                 06             \
    right_padding                06             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^(Calculator|Music|1Password|QMK Toolbox|Finder|System Preferences|Parallels|Slack|Messages|DisplayLinkUserAgent)$" manage=off
yabai -m rule --add app="^(Better|Dropbox|GlobalProtect|Snagit 2021|OneDrive|Keyboard Maestro$|Discord$|Cisco AnyConnect Secure Mobility Client)$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Microsoft Teams" manage=off
yabai -m rule --add app="^Microsoft Teams$" title="^Microsoft Teams Notifications$" manage=off
yabai -m rule --add app="^Firefox$" title="Extension: (Tree Style Tab) - Close tabs?" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Outlook Re/Fw" app="^Microsoft Outlook$" title="^(R[eE]|F[wW])" manage=off
yabai -m rule --add app="^Microsoft Outlook$" title="^New Event$" manage=off
yabai -m rule --add label="Outlook New Messages" app="^Microsoft Outlook$" title="(@trueipsolutions.com$)" manage=off
yabai -m rule --add label="Outlook New Messages" app="^Microsoft Outlook$" title="(@singledigits.com$)" manage=off
yabai -m rule --add label="Outlook New Messages" app="^Microsoft Outlook$" title="^Untitled$" manage=off
yabai -m signal --add \
      event=application_activated \
      app="^Microsoft Teams$" \
      action='${HOME}/.config/yabai/scripts/defeat-teams'

yabai -m signal --add \
      event=window_focused \
      app="^Microsoft Teams$" \
      title="^Microsoft Teams Notification$" \
      action='${HOME}/.config/yabai/scripts/defeat-teams'

echo "yabai configuration loaded.."
